---
driver:
  name: vagrant
  gui: true
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  data_bags_path: data_bags
  client_rb:
    add_formatter: <%= ENV['CI'] == 'true' ? 'minimal' : 'doc' %>

platforms:
  - name: ubuntu1404
    driver_config:
      box: ubuntu/trusty64
    provisioner:
      require_chef_omnibus: '12.6.0'

suites:
  - name: default
    run_list:
      - recipe[linux-build-server::default]
